/**
 * Whitepaper types and helpers for the website.
 *
 * The actual whitepaper data is fetched at build time from the manifest
 * generated by the docs repo:
 *
 *     https://docs.nanocollective.org/whitepapers.json
 *
 * That manifest is generated by docs/scripts/generate-whitepapers-manifest.ts
 * and kept in sync via the `whitepapers-manifest` GitHub Action whenever a
 * whitepaper's frontmatter changes. The frontmatter in
 * docs/content/collective/whitepapers/<slug>.md is the single source of truth.
 *
 * Use fetchWhitepapers() in getStaticProps to pull the manifest. The page
 * receives Whitepaper[] as props.
 *
 * The canonical lifecycle is documented at:
 * https://docs.nanocollective.org/collective/projects/how-a-project-comes-to-life
 */

export type WhitepaperStatus =
  | "Draft"
  | "In public review"
  | "Build approved"
  | "Building"
  | "Shipped"
  | "Paused"
  | "Declined"
  | "Superseded";

export interface Whitepaper {
  slug: string;
  title: string;
  description: string;
  proposer?: string;
  proposerGithub?: string;
  status?: WhitepaperStatus;
  reviewOpens?: string;
  reviewCloses?: string;
}

interface ManifestEntry {
  slug: string;
  title: string;
  description: string;
  proposer?: string;
  proposer_github?: string;
  status?: string;
  review_opens?: string;
  review_closes?: string;
}

interface Manifest {
  generated_at: string;
  count: number;
  whitepapers: ManifestEntry[];
}

const MANIFEST_URL = "https://docs.nanocollective.org/whitepapers.json";

function normalise(entry: ManifestEntry): Whitepaper {
  // Strip "(working title)" or similar trailing parentheticals for cleaner
  // surfacing on the website. Docs site keeps the working-title suffix.
  const title = entry.title.replace(/\s*\([^)]*\)\s*$/, "");
  return {
    slug: entry.slug,
    title,
    description: entry.description,
    proposer: entry.proposer,
    proposerGithub: entry.proposer_github,
    status: entry.status as WhitepaperStatus | undefined,
    reviewOpens: entry.review_opens,
    reviewCloses: entry.review_closes,
  };
}

export async function fetchWhitepapers(): Promise<Whitepaper[]> {
  try {
    const res = await fetch(MANIFEST_URL, {
      // Always go to network in builds; no Next data cache.
      cache: "no-store",
    });
    if (!res.ok) {
      console.error(
        `Failed to fetch whitepapers manifest: ${res.status} ${res.statusText}`,
      );
      return [];
    }
    const data = (await res.json()) as Manifest;
    return data.whitepapers.map(normalise);
  } catch (error) {
    console.error("Error fetching whitepapers manifest:", error);
    return [];
  }
}

export function getActiveWhitepapers(all: Whitepaper[]): Whitepaper[] {
  const active: WhitepaperStatus[] = [
    "In public review",
    "Build approved",
    "Building",
  ];
  return all.filter((w) => w.status && active.includes(w.status));
}

export function getInReviewWhitepapers(all: Whitepaper[]): Whitepaper[] {
  return all.filter((w) => w.status === "In public review");
}

export function daysUntil(iso: string): number | null {
  const target = new Date(iso);
  if (Number.isNaN(target.getTime())) return null;
  const now = new Date();
  const diff = target.getTime() - now.getTime();
  return Math.ceil(diff / (1000 * 60 * 60 * 24));
}

export function docsUrlFor(slug: string): string {
  return `https://docs.nanocollective.org/collective/whitepapers/${slug}`;
}
